### ISSUE TITLE
If backend is stoped in middle of LongRunningJob it will get stuck in the db forever

### ISSUE THREAD

**Issue by guysoft** [hooram/ownphotos-backend#48]
Steps to reproduce:
1. start ownphotos
2. run a directory scan with a large directory (few hundred images)
3. stop containers/process before its finished.
4. start service

Expected:
All stuck db jobs should be cleaned .

Actual:
Job hangs finished_at field has NULL.
The issue can be seen using Adminer, looks like this:
![screenshot_20181226_021308](https://user-images.githubusercontent.com/325670/50427550-ccd21900-08b3-11e9-8e2e-acb20341f045.png)

**Comment by gregbert42** [comment]
How does one get the view you show in your post?

**Comment by guysoft** [comment]
@gregbert42

You append to your ``docker-compose.yml``:
```
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: ownphotos-adminer
    links:
      - "ownphotos-db:db"
```
Then ``docker-compose up -d``

Then access it via port ``8080``, login using your posgres as user, db as host and password are your set password. From there you can find the table and click the "select" word next to its name.
