### ISSUE TITLE
Small face thumbnail missing on "Label Faces" modal

### ISSUE THREAD

**Issue by isleshocky77** [hooram/ownphotos-backend#65]
When on the "Label Faces" modal, the small face thumbnail on the top left is missing. When inspecting it looks like this:

```html
<img auth="[object Object]" height="40" width="40" src="http://backend/media/faces/c5291c1156b701f0b5d4ff2cc10545a74_0.jpg" class="ui image">
```

*Note* http://backend

I'm running this by checking out the `dev` branch and using `docker-compose up`. 
I've tweaked the `docker-compose.yml` file only by changing all `3000` to `3007` and updating `BACKEND_HOST` to `machine.local:3007`.  I'm wondering if the proxy is handling this correctly with `3000` being hard-coded into the [nginx config file](https://github.com/guysoft/ownphotos-proxy/blob/master/nginx.conf).

*Note 2* If I replace "http://backend/media/faces/c5291c1156b701f0b5d4ff2cc10545a74_0.jpg" with "http://machine.local:3007/media/faces/c5291c1156b701f0b5d4ff2cc10545a74_0.jpg", the file does exist correctly.  I'm not seeing this issue on any of the other images in the system so far.

**Comment by guysoft** [comment]
Can you post your ``doker-compose.yml``?
you can remove the passwords if that is an issue.

**Comment by isleshocky77** [comment]
```yml
version: '2'

services:

  proxy:
    image: guysoft/ownphotos-proxy
    tty: true
    container_name: ownphotos-proxy
    restart: always
    links:
      - "backend:backend"
      - "frontend:frontend"
    ports:
      - "3007:80"
      
  ownphotos-db:
    image: postgres
    container_name: ownphotos-db
    restart: always
    environment:
    # This db password is internal, you can change it if you want, but also change it in ownphotos-backend container
      - POSTGRES_PASSWORD=AaAa1234
      - POSTGRES_DB=ownphotos
    volumes:
      - ownphotos-data:/var/lib/postgresql/data

  frontend:
    container_name: ownphotos-frontend
    image: guysoft/ownphotos-frontend:dev
    tty: true
    environment:
       # This is the path to the backend host public facing. if your website is ownphotos.org then this should be "ownphotos.org".
       # Default here is assuming you are running on localhost on port 3000 as given in ownphotos-proxy service
      - BACKEND_HOST=ducks.local:3007
    links:
      - "backend:backend"

  backend:
    image: hooram/ownphotos:dev
    # For development uncomment this and comment the image name above
    #build: .
    container_name: ownphotos-backend
    volumes:
      # Your photos go here
      - $HOME/Pictures/:/data
      - media:/code/media
    environment:
      - SECRET_KEY=change_meme
      # This is backend host from within the service, you dont need to change this
      - BACKEND_HOST=backend
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_USERNAME=admin
      # Change your admin password!
      - ADMIN_PASSWORD=admin
      - DEBUG=true
      - DB_BACKEND=postgresql
      - DB_NAME=ownphotos
      - DB_USER=postgres
      # This db password is internal, you can change it if you want, but also change it in ownphotos-db container
      - DB_PASS=AaAa1234
      - DB_HOST=ownphotos-db
      - DB_PORT=5432
      - REDIS_HOST=ownphotos-redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=CHANGE_MEAAAA
    links:
      - "ownphotos-db:ownphotos-db"
      - "ownphotos-redis:ownphotos-redis"
  
  ownphotos-redis:
    image: redis
    container_name: ownphotos-redis

volumes:
  ownphotos-data:
  media:
```
